#Please make sure if your creating an Dockerfile and want to test it localy, 
#to rebuild the basImage:latest for getting all the files you changed in your app Image you want to create
FROM node:lts-alpine3.16 as builder
ARG NODE_ENV
ARG BUILD_FLAG
WORKDIR /app/builder
COPY . .
RUN npm i