version: "3.8"
networks:
  corp:
    driver: bridge
services:
  base:
    container_name: nx_local_baseImage
    build:
      context: ./
      cache_from:
        - nx_local_baseImage:latest
      dockerfile: Dockerfile.local
  backend:
    container_name: backend
    build:
      context: ./
      cache_from:
        - nx_local_baseImage:latest
      dockerfile: ./apps/backend/Dockerfile.local
      args:
        NODE_ENV: "development"
        BUILD_FLAG: ""
    image: backend:nx-dev
    ports:
      - 4939:4939
    environment:
      NODE_ENV: "development"
      PORT: 4939
    networks:
      - corp
    restart: on-failure
  frontend:
    container_name: frontend
    build:
      context: ./
      cache_from:
        - nginx:1.19.2
      dockerfile: ./apps/frontend/Dockerfile.local
      args:
        NODE_ENV: "development"
        BUILD_FLAG: ""
    image: frontend:nx-dev
    ports:
      - 4200:80
    environment:
      NODE_ENV: "development"
      PORT: 4200
    networks:
      - corp
    restart: on-failure