#Please make sure if your creating an Dockerfile and want to test it localy, to rebuild the basImage:latest for getting all the files you changed
FROM nx_local_baseImage:latest AS builder

ARG NODE_ENV
ARG BUILD_FLAG
WORKDIR /app/builder
COPY . .
RUN npx nx build backend ${BUILD_FLAG}

FROM nx_local_baseImage:latest

WORKDIR /app
COPY --from=builder /app/builder ./
ENV NODE_ENV=$NODE_ENV

CMD ["node", "./dist/apps/backend/main.js"]