name: Merging code to the release (main) branch, promoting it from staging to production enviroment in Heroku
run-name: Merging to main, deploy from staging to production 
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  deploy-from-staging-toproduction:
    runs-on: ubuntu-latest
    steps:
    - name: REST API for deploying NestJS Backend to production enviroment
      run: |
        curl -n -X POST https://api.heroku.com/pipeline-promotions \
        -d '{
        "pipeline": {
          "id": "${{ secrets.PIP_B_ID }}"
        },
        "source": {
          "app": {
            "id": "${{ secrets.STAG_B_ID }}"
           }
        },
         "targets": [
            {
               "app": {
                  "id": "${{ secrets.PROB_B_ID }}"
                }
            }
          ]
        }' \
          -H "Content-Type: application/json" \
          -H "Accept: application/vnd.heroku+json; version=3"
    - name: REST API for deploying AngularJS Frontend to production enviroment
      run: |
        curl -n -X POST https://api.heroku.com/pipeline-promotions \
        -d '{
        "pipeline": {
          "id": "${{ secrets.PIP_F_ID }}"
        },
        "source": {
          "app": {
            "id": "${{ secrets.STAG_F_ID }}"
           }
        },
         "targets": [
            {
               "app": {
                  "id": "${{ secrets.PROB_F_ID }}"
                }
            }
          ]
        }' \
          -H "Authorization: ${{ secrets.HEROKU_API_KEY }}" \ 
          -H "Content-Type: application/json" \
          -H "Accept: application/vnd.heroku+json; version=3"